# Generated by Django 3.0.5 on 2020-04-10 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Create at')),
                ('schedule', models.DateTimeField(verbose_name='Schedule')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('event_type', models.CharField(choices=[('RETRO', 'Retro Meeting')], default='RETRO', max_length=20, verbose_name='event type')),
                ('achieved', models.BooleanField(default=False, verbose_name='Completed')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
