# Generated by Django 3.0.5 on 2020-04-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceremonies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceremony',
            options={'verbose_name_plural': 'Ceremonies'},
        ),
    ]
