# Generated by Django 3.0.5 on 2020-04-10 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceremonies', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('title', models.CharField(max_length=150)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ceremonies.Ceremony', verbose_name='ceremony')),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='elements.Column')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
