# Generated by Django 3.0.5 on 2020-04-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceremonies', '0002_auto_20200410_2158'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_message', models.TextField(blank=True, null=True, verbose_name='Intro message')),
                ('conclusion_message', models.TextField(blank=True, null=True, verbose_name='Conclusion message')),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='ceremonies.Ceremony', verbose_name='ceremony')),
            ],
        ),
        migrations.RemoveField(
            model_name='postit',
            name='ceremony',
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='elements.Board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='elements.Column')),
            ],
        ),
        migrations.AlterField(
            model_name='postit',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='elements.BoardColumn'),
        ),
    ]
